name: Lint
on:
  push:
    branches:
      - '**'
  pull_request:
  workflow_dispatch:

permissions: {}

jobs:
  lint:
    runs-on: ubuntu-slim
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.14'
          pip-install: PyYAML

      - name: Lint
        run: python framework/lint.py
